---
scireum_volumes: &scireum_volumes
  - name: docker_socket
    path: /var/run/docker.sock
  - name: m2
    path: /root/.m2

kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 100

steps:
  - name: compile
    image: scireum/sirius-build-jdk18
    commands:
      - mvn clean compile
    volumes: *scireum_volumes
    when:
      branch:
        - master
      event:
        - push

  - name: cron_unit_tests
    image: scireum/sirius-build-jdk18
    commands:
      - mvn clean test
    volumes: *scireum_volumes
    when:
      event:
        - cron

  - name: cron_report_failures
    image: plugins/slack
    settings:
      webhook: https://memoio.com/endpoint/hook/4b17b22e54124c53ab2e550cf3311461cba7c66a1e3756fa8d17e7dc17a48dbb
      channel: scireum-dev
    when:
      status:
        - failure
      event:
        - cron

  - name: test
    image: scireum/sirius-build-jdk18
    commands:
      - mvn clean test -Dtest.excluded.groups=nightly
    volumes: *scireum_volumes
    when:
      event:
        - pull_request

  - name: deploy
    image: scireum/sirius-build-jdk18
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean deploy -DskipTests
    volumes: *scireum_volumes
    when:
      event:
        - tag

  - name: sonar
    image: scireum/sirius-build-jdk18
    commands:
      - sed -i 's/DEVELOPMENT-SNAPSHOT/${DRONE_TAG}/g' pom.xml
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=${DRONE_REPO_NAME}
    volumes: *scireum_volumes
    when:
      event:
        - tag

  - name: notify-tag-build
    image: plugins/slack
    settings:
      webhook: https://memoio.com/endpoint/hook/4b17b22e54124c53ab2e550cf3311461cba7c66a1e3756fa8d17e7dc17a48dbb
      channel: scireum-dev
      template: "{{Repo.Name}}: {{Build.Tag}}"
    when:
      event:
        - tag

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
  - name: m2
    host:
      path: /root/.m2
