name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]

    container:
      image: scireum/sirius-build-jdk26
      volumes:
        - /root/.m2:/root/.m2
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v7.0.1

      - name: Test project including nightly tests
        run: mvn clean test

      - name: Report failure to Memoio scireum-dev
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "channel": "scireum-dev",
            "text": "Nightly Tests failed for **${{ github.repository }}**: [Details](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }' ${{ secrets.MEMOIO_SCIREUM_DEV }}
