name: Automatic Release on SemVer Tag on Main Branch

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release if none exists
        run: gh release view "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" || gh release create "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" --verify-tag --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
