name: SonarQube Analysis
on:
  push:
    branches:
      - feature/ymo/DO-409-mvn-sonar

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    container:
      image: scireum/sirius-build-jdk23
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Replace version in pom.xml
        run: sed -i 's/DEVELOPMENT-SNAPSHOT/sonar-test/g' pom.xml

      - name: Analyze project with SonarQube
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=scireum_sirius-kernel_81e9dc44-1749-4a49-a1f6-686fdb86bad3 -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.organization=scireum
